Add Output Ordering Feature for GNCOA and EEDB COA in ACCERT
accert-dev/ACCERT pull request #37
Opened 2024-09-20 19:21 UTC by JiaZhou-PU

**What issue does this change request address?**
Address #33 

**What are the changes due to this change request?**
This PR introduces a new feature to ACCERT that provides users with the ability to choose between two output formats

1. **GN_COA (Generalized Nuclear Code of Accounts )**: 
   - ACCERT now supports generating output ordered by GNCOA

2. **EEDB COA (Energy Economic Database Code of Accounts)**: 
   - Users can also opt to output results based on the traditional EEDB COA format.

----------------
For Change Request Review
----------------
- [ ] 1. Is the merge request reference an issue?  If the issue is closed, the issue close checklist shall be done.
- [ ] 2. Is the merge request reference a task?  If the task is fulfilled, the task close checklist shall be done.
- [ ] 3. If any changes to the database, there must be an accompanying change to the all the linked tables.

2024-09-20 19:27 UTC, JiaZhou-PU commented
sample GNCOA output using GNCOA:
```
=============================== Generating results table for review ================================


+------------+-------------------------------------------------+------------+----------+------------------+
|   gncoa    |               account_description               | total_cost | gn_level |  review_status   |
+------------+-------------------------------------------------+------------+----------+------------------+
| 20         | TOTAL DIRECT COST                               |   2,512.96 |    0     |     Updated      |
|  21        | Structures and improvements subtotal            |     525.33 |    1     |     Updated      |
|   211      | Yardwork                                        |      71.45 |    2     | Ready for Review |
|   212      | Reactor Island Civil Structures                 |     185.50 |    2     |     Updated      |
|    212.1   | Reactor containment building                    |     182.70 |    3     |    Unchanged     |
|    212.2   | Manway Tnls. (Radiological Ctrl Access Tunnels) |       2.17 |    3     |    Unchanged     |
|    212.3   | Containment Equipment Hatch Missile Shield      |       0.63 |    3     |    Unchanged     |
|   213      | Main Function Buildings                         |     134.61 |    2     |     Updated      |
|    213.1   | Turbine room and heater bay                     |      59.27 |    3     | Ready for Review |
|    213.21  | Control Room/Diesel Generator Building          |      51.57 |    3     |    Unchanged     |
|    213.22  | Control Rm Emergency Air Intake Building        |       0.25 |    3     |    Unchanged     |
|    213.31  | Main Steam + Feedwater Pipe Enc.                |      22.42 |    3     |    Unchanged     |
|    213.32  | Pipe Tunnels                                    |       0.90 |    3     |    Unchanged     |
|    213.4   | Elec. Tunnels                                   |       0.19 |    3     |    Unchanged     |
|   214      | Buildings to Support Main Function              |      92.83 |    2     |     Updated      |
|    214.1   | Fuel storage building                           |      28.15 |    3     |    User Input    |
|    214.2   | Primary auxiliary building and tunnels          |      52.63 |    3     |    Unchanged     |
|    214.3   | Waste Water Treatment                           |       2.19 |    3     |    Unchanged     |
|    214.5   | Fire Pump House, Including Foundations          |       1.22 |    3     |    Unchanged     |
|    214.6   | Non- Essen. Switchgear Bldg.                    |       1.53 |    3     |    Unchanged     |
|    214.7   | Emergency Feed Pump Building                    |       7.12 |    3     |    Unchanged     |
|   215      | Waste processing building                       |      40.94 |    2     |    Unchanged     |
|   216      | Other structures                                |      25.07 |    2     |     Updated      |
|    216.1   | Administration + Services Building              |      18.94 |    3     |    Unchanged     |
|    216.2   | Security building                               |       3.88 |    3     |    Unchanged     |
|    216.4   | Technical Support Center                        |       2.25 |    3     |    Unchanged     |
|  22        | Reactor plant equipment                         |     873.00 |    1     |     Updated      |
|   221      | Reactor equipment                               |     197.53 |    2     |     Updated      |
|    221.11  | Reactor Support (Field Cost 221)                |       3.91 |    3     |    Unchanged     |
|    221.121 | Vessel Structure (NSSS)                         |      80.99 |    3     | Ready for Review |
|    221.122 | Vessel Structure (Field Cost 221)               |       7.83 |    3     | Ready for Review |
|    221.131 | Lower Internals (NSSS)                          |      31.78 |    3     |    Unchanged     |
|    221.132 | Upper Internals (NSSS)                          |      31.78 |    3     |    Unchanged     |
|    221.133 | Vessel Internals (Field Cost 221)               |       1.70 |    3     |    Unchanged     |
|    221.211 | Control Rods (NSSS)                             |       3.10 |    3     |    Unchanged     |
|    221.212 | Control Rod Drives (NSSS)                       |      34.90 |    3     |    Unchanged     |
|    221.213 | Control Rod System (Field Cost 221)             |       1.53 |    3     |    Unchanged     |
|   222      | Main heat transfer transport system             |     321.55 |    2     |     Updated      |
|    222.11  | Main Coolant Pumps (NSSS)                       |     125.24 |    3     |    Unchanged     |
|    222.12  | Fluid Circulation Drive System (Field Cost 222) |       7.51 |    3     | Ready for Review |
|    222.21  | Reactor Coolant Piping (NSSS)                   |      11.40 |    3     |    Unchanged     |
|    222.22  | Reactor Coolant Piping System (Field Cost 222)  |      14.77 |    3     | Ready for Review |
|    222.31  | Steam Generators (NSSS)                         |     149.80 |    3     |    Unchanged     |
|    222.32  | Steam Generator Equipment (Field Cost 222)      |       2.39 |    3     |    Unchanged     |
|    222.41  | Pressurizer (NSSS)                              |       8.30 |    3     |    Unchanged     |
|    222.42  | Pressurizer Relief Tank (NSSS)                  |       1.85 |    3     |    Unchanged     |
|    222.43  | Pressurizing System (Field Cost 222)            |       0.28 |    3     | Ready for Review |
|   223      | Safeguards system                               |      61.59 |    2     |     Updated      |
|    223.11  | Residual Heat Removal Pumps & Drives (NSSS)     |       1.94 |    3     |    Unchanged     |
|    223.12  | Residual Heat Removal Heat Exchanger (NSSS)     |       6.26 |    3     |    Unchanged     |
|    223.13  | Residual Heat Removal Sys (Field Cost 223)      |       6.81 |    3     |    Unchanged     |
|    223.31  | Safety Injection Pumps And Drives (NSSS)        |       1.72 |    3     |    Unchanged     |
|    223.32  | Accumulator Tank (NSSS)                         |      15.30 |    3     |    Unchanged     |
|    223.33  | Boron Injection Tank (NSSS)                     |       0.90 |    3     |    Unchanged     |
|    223.34  | Boron Injection Surge Tank (NSSS)               |       0.05 |    3     |    Unchanged     |
|    223.35  | Boron Injection Recirc. Pump & Drives (NSSS)    |       0.04 |    3     |    Unchanged     |
|    223.36  | Safety Injection System (Field Cost 223)        |      10.38 |    3     |    Unchanged     |
|    223.4   | Containment Spray System (Field Cost 223)       |      15.11 |    3     |    Unchanged     |
|    223.5   | Combustible Gas Control System (Field Cost 223) |       3.08 |    3     |    Unchanged     |
|   224      | Radwaste processing                             |      59.67 |    2     |    Unchanged     |
|   225      | Fuel Handling Systems                           |      11.93 |    2     |     Updated      |
|    225.1   | Fuel Handling Tools (NSSS)                      |       0.40 |    3     |    Unchanged     |
|    225.2   | Fuel handling and storage                       |       9.02 |    3     |    Unchanged     |
|    225.3   | Fuel Storage Racks (NSSS)                       |       2.51 |    3     |    Unchanged     |
|   226      | Other reactor plant equipment                   |     112.99 |    2     |     Updated      |
|    226.1   | Inert Gas Sys                                   |       3.53 |    3     |    Unchanged     |
|    226.2   | Reactor Makeup Water Sys                        |       4.25 |    3     |    Unchanged     |
|    226.31  | Rotating Machinery (Pumps And Motors) (NSSS)    |       2.22 |    3     |    Unchanged     |
|    226.32  | Heat Transfer Equipment (NSSS)                  |       2.45 |    3     |    Unchanged     |
|    226.33  | Tanks And Pressure Vessels (NSSS)               |       1.14 |    3   [...]

2024-09-20 19:45 UTC, JiaZhou-PU commented
Pass all tests
```
======================================= test session starts =======================================
platform darwin -- Python 3.9.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jia.zhou/Library/CloudStorage/Box-Box/ACCERT/repo/ACCERT/test
plugins: anyio-2.2.0
collected 33 items

test_integration.py ....                                                                    [ 12%]
test_main.py ........................                                                       [ 84%]
test_mysql.py ....                                                                          [ 96%]
test_util.py .                                                                              [100%]

======================================= 33 passed in 10.38s =======================================
```

2024-09-20 19:47 UTC, JiaZhou-PU commented
@cbolisetti @nstauff Ready for review

2024-09-23 15:16 UTC, nstauff approved these changes
Looks good to me.

2024-09-24 16:52 UTC, cbolisetti requested changes
Hi @JiaZhou-PU, this looks good, thank you for all the hard work! 
The only change I would suggest is removing the description in parantheses in the GNCOA like "field cost 221" and "NSSS". From my understanding, when EEDB COA says "Field Cost 221" it means that it is essentially site labor cost for assembly, and "NSSS" refers to equipment cost. I understand you already put those in the corresponding cost elements in GNCOA, correct? If so, we won't need the description in the parentheses.

2024-09-24 22:07 UTC, JiaZhou-PU commented
@cbolisetti Got it, I put a mapping file in database
```
+------------+-------------------------------------------------------------------------+------------+----------+------------------+
|   gncoa    |                            gncoa_description                            | total_cost | gn_level |  review_status   |
+------------+-------------------------------------------------------------------------+------------+----------+------------------+
| 20         | Capitalized Direct Costs                                                |   2,512.96 |    0     |     Updated      |
|  21        | Structures and Improvements                                             |     525.33 |    1     |     Updated      |
|   211      | Site Preparation/Yard Work                                              |      71.45 |    2     | Ready for Review |
|   212      | Reactor Island Civil Structures                                         |     185.50 |    2     |     Updated      |
|    212.1   | Reactor containment building                                            |     182.70 |    3     |    Unchanged     |
|    212.2   | Manway Tnls. (Radiological Ctrl Access Tunnels)                         |       2.17 |    3     |    Unchanged     |
|    212.3   | Containment Equipment Hatch Missile Shield                              |       0.63 |    3     |    Unchanged     |
|   213      | Main Function Buildings                                                 |     134.61 |    2     |     Updated      |
|    213.1   | Energy Conversion Building                                              |      59.27 |    3     | Ready for Review |
|    213.21  | Control Room/Diesel Generator Building                                  |      51.57 |    3     |    Unchanged     |
|    213.22  | Control Rm Emergency Air Intake Building                                |       0.25 |    3     |    Unchanged     |
|    213.31  | Main Steam + Feedwater Pipe Enc.                                        |      22.42 |    3     |    Unchanged     |
|    213.32  | Pipe Tunnels                                                            |       0.90 |    3     |    Unchanged     |
|    213.4   | Electrical Tunnels                                                      |       0.19 |    3     |    Unchanged     |
|   214      | Buildings to Support Main Function                                      |      92.83 |    2     |     Updated      |
|    214.1   | Spent Fuel Management Building                                          |      28.15 |    3     |    User Input    |
|    214.2   | Balance of Plant Service Building                                       |      52.63 |    3     |    Unchanged     |
|    214.3   | Wastewater Treatment Building                                           |       2.19 |    3     |    Unchanged     |
|    214.5   | Fire Protection Building                                                |       1.22 |    3     |    Unchanged     |
|    214.6   | Non-essential Switchgear Building                                       |       1.53 |    3     |    Unchanged     |
|    214.7   | Emergency and Start-up Power Systems                                    |       7.12 |    3     |    Unchanged     |
|   215      | Supply Chain Buildings                                                  |      40.94 |    2     |    Unchanged     |
|   216      | Human Resources Buildings                                               |      25.07 |    2     |     Updated      |
|    216.1   | Administration Building                                                 |      18.94 |    3     |    Unchanged     |
|    216.2   | Security Building and Gatehouse                                         |       3.88 |    3     |    Unchanged     |
|    216.4   | Operation and Maintenance (O&M) Center                                  |       2.25 |    3     |    Unchanged     |
|  22        | Structures and Improvements                                             |     873.00 |    1     |     Updated      |
|   221      | Reactor Components                                                      |     197.53 |    2     |     Updated      |
|    221.11  | Reactor support                                                         |       3.91 |    3     |    Unchanged     |
|    221.121 | Outer vessel structure equip                                            |      80.99 |    3     | Ready for Review |
|    221.122 | Outer vessel structure field                                            |       7.83 |    3     | Ready for Review |
|    221.131 | Inner vessel structure lower                                            |      31.78 |    3     |    Unchanged     |
|    221.132 | Inner vessel structure uppper                                           |      31.78 |    3     |    Unchanged     |
|    221.133 | Inner vessel structure field                                            |       1.70 |    3     |    Unchanged     |
|    221.211 | Reactivity control system control rods                                  |       3.10 |    3     |    Unchanged     |
|    221.212 | Reactivity control system control drivers                               |      34.90 |    3     |    Unchanged     |
|    221.213 | Reactivity control system field                                         |       1.53 |    3     |    Unchanged     |
|   222      | Main heat transfer system                                               |     321.55 |    2     |     Updated      |
|    222.11  | Fluid circulation drive system Equip                                    |     125.24 |    3     |    Unchanged     |
|    222.12  | Fluid circulation drive system Field                                    |       7.51 |    3     | Ready for Review |
|    222.21  | Reactor heat transfer piping system Equip                               |      11.40 |    3     |    Unchanged     |
|    222.22  | Reactor heat transfer piping system  Field                              |      14.77 |    3     | Ready for Review |
|    222.31  | Heat exchangers Equip                                                   |     149.80 |    3     |    Unchanged     |
|    222.32  | Heat exchangers  Field                                                  |       2.39 |    3     |    Unchanged     |
|    222.41  | Pressurizer system Equip                                                |       8.30 |    3     |    Unchanged     |
|    222.42  | Pressurizer system Relief Tank Equip                                    |       1.85 |    3     |    Unchanged     |
|    222.43  | Pressurizer system Field                                                |       0.28 |    3     | Ready for Review |
|   223      | Safety Systems                                                          |      61.59 |    2     |     Updated      |
|    223.11  | Internal Residual Heat Removal System Pumps & Drives                    |       1.94 |    3     |    Unchanged     |
|    223.12  | Internal Residual Heat Removal System Heat Exchanger                    |       6.26 |    3     |    Unchanged     |
|    223.13  | Internal Residual Heat Removal System Others                            |       6.81 |    3     |    Unchanged     |
|    223.31  | Reactivity Safety Injection System Pumps And Drives                     |       1.72 |    3     |    Unchanged     |
|    223.32  | Reactivity Safety Injection System Accumulator Tank                     |      15.30 |    3     |    Unchanged     |
|    223.33  | Reactivity Safety Injection System Boron Injection Tank                 |       0.90 |    3     |    Unchanged     |
|    223.34  | Reactivity Safety Injection System Boron Injection Surge Tank           |       0.05 |    3     |    Unchanged     |
|    223.35  | Reactivity Safety Injection System Boron Injection Recirc. Pump, Drives |       0.04 |    3     |    Unchanged     |
|    223.36  | Reactivity Safety Injection System Others                               |      10.38 |    3     |    Unchanged     |
|    223.4   | Containm [...]

2024-09-24 22:08 UTC, JiaZhou-PU commented
@cbolisetti pass all tests

```
============================================== test session starts ===============================================
platform darwin -- Python 3.9.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jia.zhou/Library/CloudStorage/Box-Box/ACCERT/repo/ACCERT/test
plugins: anyio-2.2.0
collected 33 items

test_integration.py ....                                                                                   [ 12%]
test_main.py ........................                                                                      [ 84%]
test_mysql.py ....                                                                                         [ 96%]
test_util.py .                                                                                             [100%]

=============================================== 33 passed in 8.62s ===============================================

2024-09-25 20:06 UTC, JiaZhou-PU commented
@cbolisetti 
```
============================== Generating results table for review ================================


+-----------+----------------------------------------------------------+------------+----------+------------------+
|   gncoa   |                    gncoa_description                     | total_cost | gn_level |  review_status   |
+-----------+----------------------------------------------------------+------------+----------+------------------+
| 20        | Capitalized Direct Costs                                 |   2,512.96 |    0     |     Updated      |
|  21       | Structures and Improvements                              |     525.33 |    1     |     Updated      |
|   211     | Site Preparation/Yard Work                               |      71.45 |    2     | Ready for Review |
|   212     | Reactor Island Civil Structures                          |     185.50 |    2     |     Updated      |
|    212.1  | Reactor containment building                             |     182.70 |    3     |    Unchanged     |
|    212.2  | Manway Tnls. (Radiological Ctrl Access Tunnels)          |       2.17 |    3     |    Unchanged     |
|    212.3  | Containment Equipment Hatch Missile Shield               |       0.63 |    3     |    Unchanged     |
|   213     | Main Function Buildings                                  |     134.61 |    2     |     Updated      |
|    213.1  | Energy Conversion Building                               |      59.27 |    3     | Ready for Review |
|    213.21 | Control Room/Diesel Generator Building                   |      51.57 |    3     |    Unchanged     |
|    213.22 | Control Rm Emergency Air Intake Building                 |       0.25 |    3     |    Unchanged     |
|    213.31 | Main Steam + Feedwater Pipe Enc.                         |      22.42 |    3     |    Unchanged     |
|    213.32 | Pipe Tunnels                                             |       0.90 |    3     |    Unchanged     |
|    213.4  | Electrical Tunnels                                       |       0.19 |    3     |    Unchanged     |
|   214     | Buildings to Support Main Function                       |      92.83 |    2     |     Updated      |
|    214.1  | Spent Fuel Management Building                           |      28.15 |    3     |    User Input    |
|    214.2  | Balance of Plant Service Building                        |      52.63 |    3     |    Unchanged     |
|    214.3  | Wastewater Treatment Building                            |       2.19 |    3     |    Unchanged     |
|    214.5  | Fire Protection Building                                 |       1.22 |    3     |    Unchanged     |
|    214.6  | Non-essential Switchgear Building                        |       1.53 |    3     |    Unchanged     |
|    214.7  | Emergency and Start-up Power Systems                     |       7.12 |    3     |    Unchanged     |
|   215     | Supply Chain Buildings                                   |      40.94 |    2     |    Unchanged     |
|   216     | Human Resources Buildings                                |      25.07 |    2     |     Updated      |
|    216.1  | Administration Building                                  |      18.94 |    3     |    Unchanged     |
|    216.2  | Security Building and Gatehouse                          |       3.88 |    3     |    Unchanged     |
|    216.4  | Operation and Maintenance (O&M) Center                   |       2.25 |    3     |    Unchanged     |
|  22       | Structures and Improvements                              |     873.00 |    1     |     Updated      |
|   221     | Reactor Components                                       |     197.53 |    2     |     Updated      |
|    221.11 | Reactor support                                          |       3.91 |    3     |    Unchanged     |
|    221.12 | Outer vessel structure                                   |      88.83 |    3     |     Updated      |
|    221.13 | Inner vessel structure                                   |      65.26 |    3     |     Updated      |
|    221.2  | Reactivity control system                                |      39.53 |    3     |     Updated      |
|   222     | Main heat transfer system                                |     321.55 |    2     |     Updated      |
|    222.1  | Fluid circulation drive system                           |     132.75 |    3     |     Updated      |
|    222.2  | Reactor heat transfer piping system                      |      26.17 |    3     |     Updated      |
|    222.3  | Heat exchangers                                          |     152.19 |    3     |     Updated      |
|    222.4  | Pressurizer system                                       |      10.43 |    3     |     Updated      |
|   223     | Safety Systems                                           |      61.59 |    2     |     Updated      |
|    223.1  | Internal Residual Heat Removal System                    |      15.01 |    3     |     Updated      |
|    223.3  | Reactivity Safety Injection System                       |      28.39 |    3     |     Updated      |
|    223.4  | Containment Spray System                                 |      15.11 |    3     |    Unchanged     |
|    223.5  | Combustible Gas Control System                           |       3.08 |    3     |    Unchanged     |
|   224     | Radioactive Byproduct Processing Systems                 |      59.67 |    2     |    Unchanged     |
|   225     | Fuel Handling Systems                                    |      11.93 |    2     |     Updated      |
|    225.1  | Core Refueling Equipment                                 |       0.40 |    3     |    Unchanged     |
|    225.2  | Ex-Core Operational Fuel Handling Equipment              |       9.02 |    3     |    Unchanged     |
|    225.3  | Fuel Handling Systems Other                              |       2.51 |    3     |    Unchanged     |
|   226     | Other Reactor Plant Equipment                            |     112.99 |    2     |     Updated      |
|    226.1  | Other Reactor Plant Equipment Inert Gas Sys              |       3.53 |    3     |    Unchanged     |
|    226.2  | Other Reactor Plant Equipment Reactor Makeup Water Sys   |       4.25 |    3     |    Unchanged     |
|    226.3  | Other Reactor Plant Equipment Coolant treatment systems  |      43.91 |    3     |     Updated      |
|    226.6  | Other Reactor Plant Equipment Fluid Leak Detection Sys   |       0.49 |    3     |    Unchanged     |
|    226.7  | Other Reactor Plant Equipment Aux Cool Sys               |      48.26 |    3     | Ready for Review |
|    226.8  | Other Reactor Plant Equipment Maintenance                |      10.71 |    3     |     Updated      |
|    226.9  | Other Reactor Plant Equipment Sampling Equip             |       1.83 |    3     |    Unchanged     |
|   227     | Reactor Instrumentation and Control (I&C)                |      61.42 |    2     |     Updated      |
|    227.11 | Instrumentation                                          |          0 |    3     |    Unchanged     |
|    227.12 | Reactor Control                                          |      61.42 |    3     |    Unchanged     |
|   228     | Reactor Plant Miscellaneous Items                        |      21.23 |    2     |    Unchanged     |
|  23       | Energy Conversion System                                 |     761.04 |    1     |     Updated      |
|    232.1  | Electricity Generation Systems                           |     383.06 |    3     | Ready for Review |
|    232.2  | Process Heat Export Equipment                            |      63.61 |    3     |    Unchanged     |
|   233     | Ultimate Heat Sink                                       |     213.88 |    2     |     Updated      |
|    233.1  | Water Condensing Systems                                 |     213.88 |    3     |     Updated      |
|   234     | Feed Heating Systems                                     |      60.37 |    2     | Ready for Re [...]

2024-09-25 20:19 UTC, cbolisetti approved these changes

2024-09-25 21:34 UTC, merged