Adding Necost to ACCERT
accert-dev/ACCERT pull request #44
Opened 2024-10-31 23:04 UTC by JiaZhou-PU

--------
Merge Request Description
--------
**What issue does this change request address?**
Address #43 
**What are the changes due to this change request?**
Adding NEcost and readme file for LCAE

----------------
For Change Request Review
----------------
- [ ] 1. Is the merge request reference an issue?  If the issue is closed, the issue close checklist shall be done.
- [ ] 2. Is the merge request reference a task?  If the task is fulfilled, the task close checklist shall be done.
- [ ] 3. If any changes to the database, there must be an accompanying change to the all the linked tables.

2024-10-31 23:05 UTC, JiaZhou-PU commented
@nstauff @cbolisetti ready for review

2025-04-09 18:59 UTC, nstauff requested changes
Thanks @JiaZhou-PU - main comment is to fill out some of the documentation. We need documentation filled up on the schema, and we need basic description on each new definition.

2025-04-09 18:59 UTC, nstauff commented on src/etc/necost.sch
> +        Description = "" % TODO
please provide the description here and on this schema

2025-04-09 18:59 UTC, nstauff commented on src/input_processor.py
> +import subprocess
is this Workbench library? Or did we copy it here for convenience? (it this allowed?)

2025-04-09 18:59 UTC, nstauff commented on src/necost/backend.py
> +    # Always 1 kg of product
provide description of the definition - what it does, its input/output

2025-04-09 18:59 UTC, nstauff commented on src/necost/costs.py
> +    data: pd.DataFrame,
same - provide description

2025-04-09 18:59 UTC, nstauff commented on src/necost/costs.py
> +    data: pd.DataFrame,
same

2025-04-09 18:59 UTC, nstauff commented on src/necost/frontend.py
> +    m_fabrication = (1 / (1 - data["fab_loss_percent"]))
same

2025-04-09 18:59 UTC, nstauff commented on src/necost/frontend.py
> +    fab_loss_percent = data["fab_loss_percent"]
same

2025-04-09 18:59 UTC, nstauff commented on test/test_monte_carlo_sampler.py
> +import sys
what is the purpose of this one?

2025-04-09 18:59 UTC, nstauff commented on tutorial/NECost-OT.son
> +    construction_interest_rate = 0.05
do we have anywhere description of this input in the documentation? Or is this next step?

2025-04-09 21:17 UTC, JiaZhou-PU commented on src/input_processor.py
> +import subprocess
Moved inside the function now

2025-04-10 19:04 UTC, JiaZhou-PU commented on tutorial/NECost-OT.son
> +    construction_interest_rate = 0.05
Next step

2025-04-10 19:12 UTC, JiaZhou-PU commented
The description was added @nstauff ready for review.

2025-04-10 19:34 UTC, nstauff approved these changes
Thanks @JiaZhou-PU

2025-04-10 19:35 UTC, merged